import type { Metadata } from "next";
import { Inter as FontSans, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
// import AuthProvider from "../components/AuthProvider/AuthProvider"; // Adjusted import if using TypeScript (.tsx)
import { Suspense } from "react";
// import { Analytics } from "@vercel/analytics/react";
import Providers from '@/components/providers/providers';
import { Toaster } from '@/components/ui/sonner';
import { SessionProvider } from 'next-auth/react';

import { auth } from '@/auth';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Inter({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await auth();

  return (
    // <AuthProvider>
    <SessionProvider session={session} >

      <html lang="en">
        <body
         className={font.className}>
          <Suspense>
            <Providers>
              {children}
            </Providers>
          </Suspense>

          {/* <Analytics /> */}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
    // </AuthProvider>
  );
}
